### ISSUE TITLE
Consider supporting a promise-based API

### ISSUE THREAD

**Issue by stephenmathieson** [gulpjs/empty-dir#5]
This package is great, thanks for it!

I'm wondering if you'd accept a PR which changes the async version of this package to return a Promise (rather than requiring a callback). Please let me know, as I'd be happy to make the change for you =]

**Comment by jonschlinkert** [comment]
Agreed! I'm a big fan of promises!

> I'm wondering if you'd accept a PR

That would be fantastic!

Just thinking out loud, but the API surface is so small here that perhaps we can do it in a backward-compatible way? Something like:

```js
const promise = new Promise((resolve, reject) => {
  // do stuff
});

if (typeof callback === 'function') {
  promise.then(() => callback(), callback);
  return;
}

return promise;
```

Feel free to say if you don't like this pattern or something similar. On one hand it's fun to rip off the bandaid sometimes, but on the other, it seems that any API change is probably stirring the pot for new issues to be created.  I will happily follow your lead since you are offering to do the work 😄

thoughts @stephenmathieson @tkellen?

**Comment by stephenmathieson** [comment]
Yep, that'd be fine! I'm onboard with a backwards compatible change. I just saw [this assertion](https://github.com/js-cli/js-empty-dir/blob/1.0.0/index.js#L11-L13) which made be think you'd want to break the API.

I'll see if I can make the change in the next day or so :)

**Comment by jonschlinkert** [comment]
Good point! that would indeed be a breaking change.
